Sample-Code/Sample-Code/Models/Paging.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sample_Code.Models
{
    public class Paging
    {
        ///<summary>
        /// Gets or sets Customers.
        ///</summary>
        public List<Employee> items { get; set; }

        ///<summary>
        /// Gets or sets CurrentPageIndex.
        ///</summary>
        public int CurrentPageIndex { get; set; }

        ///<summary>
        /// Gets or sets PageCount.
        ///</summary>
        public int PageCount { get; set; }

        

    }
}

Sample-Code/Sample-Code/Controllers/PagingController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sample_Code.Models;
using Sample_Code.Repository;

namespace Sample_Code.Controllers
{
    public class PagingController : Controller
    {
        private readonly IRepository<Employee> _empRepo;
        public PagingController(IRepository<Employee> empRepo)
        {
            _empRepo = empRepo;
        }

        // GET: PagingController
        public ActionResult Index()
        {
            Paging paging = new Paging();
            paging =  GetCustomers(1).Result;
            return View(paging);
        }
       
        [HttpPost]
        public ActionResult Index(int currentPageIndex)
        {
            Paging paging = new Paging();
            paging = GetCustomers(currentPageIndex).Result;
            return View(paging);          
        }

        private async Task<Paging> GetCustomers(int currentPage)
        {
            int maxRows = 4;
            Paging customerModel = new Paging();
            var emp=await _empRepo.GetAll();
            IEnumerable<Employee> employee = emp;
            int val = (currentPage - 1) * maxRows;
            customerModel.items = employee.OrderBy(p=>p.EmpId).Skip(val).Take(maxRows).ToList();
            double pageCount = (double)((decimal)employee.Count() / Convert.ToDecimal(maxRows));     
            customerModel.PageCount = (int)Math.Ceiling(pageCount);
            customerModel.CurrentPageIndex = currentPage;
            return customerModel;
        }

    }
}

Sample-Code/Sample-Code/Views/Paging/Index.cshtml
@model Paging
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h4>Employees</h4>
    <hr />
    <div class="container">
        <form asp-action="Index" asp-controller="Paging" method="post">
            <table class="table table-bordered">
                <tr>
                    <th>Employee Name</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Phone</th>
                </tr>
                @foreach (var employee in Model.items)
                {
                    <tr>
                        <td>@employee.EmpName</td>
                        <td>@employee.Email</td>
                        <td>@employee.Address</td>
                        <td>@employee.Phone</td>
                    </tr>
                }
            </table>
            <br />
            <ul class="pagination">
                <li>
                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        @if (i != Model.CurrentPageIndex)
                        {
                            <a href="javascript:PagerClick(@i);">@i</a>
                        }
                        else
                        {
                            <span>@i</span>
                        }
                    }
                </li>
            </ul>
                <input type="hidden" id="hfCurrentPageIndex" name="currentPageIndex" />
</form>
    </div>
    <script type="text/javascript">
       function PagerClick(index) {
           document.getElementById("hfCurrentPageIndex").value = index;
           document.forms[0].submit();
       }
    </script>
</body>
</html>